### ISSUE TITLE
crisp-edges not rendering properly

### ISSUE THREAD

**Issue by roxwize** [firefly-zero/fonts.fireflyzero.com#1]
[Support for the `crisp-edges` property of image-rendering is spotty](https://caniuse.com/css-crisp-edges). Chrome, Edge, Opera, and many mobile browsers support the `pixelated` value for the property but *not* `crisp-edges`; the former seems to be supported across all modern browsers. I don't know if there is any difference between the two, but using `crisp-edges` causes the fonts to render fuzzy on my browser as it's not supported.

![image](https://github.com/firefly-zero/fonts.fireflyzero.com/assets/22648124/1a29c19a-7dd2-40b8-b871-555b004fa945)

Setting it to `pixelated` and disabling `-webkit-optimize-contrast` works just fine though.

![image](https://github.com/firefly-zero/fonts.fireflyzero.com/assets/22648124/b8abcd93-2b1e-40d5-8c23-f52c72f78b3a)

**Comment by orsinium** [comment]
Thank you! Good catch. Would you like to send a PR? I'll be happy to merge it.

UPD: Here is the code: https://github.com/firefly-zero/fonts.fireflyzero.com/blob/main/templates/base.html.j2#L23-L27
